# Generated by Django 5.0.1 on 2024-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('completada', 'Completada'), ('anulada', 'Anulada'), ('no_asisten', 'No Asisten')], default='reservado', max_length=15)),
                ('personas', models.PositiveSmallIntegerField(default=1)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
